version: '3.3'
services:
  nginx:
    image: nginx
    ports:
      - "81:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi
      - spring

  fastapi:
    build: ./fastapi
    ports:
      - "8002:8000"

  spring:
    build: ./spring
    ports:
      - "8080:8080"

  mariadb:
    image: mariadb:10.6
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: recipe_db
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
